### ISSUE TITLE
Provide instructions for building xswitcher

### ISSUE THREAD

**Issue by gdbd** [ds-voix/VX-PBX#3]
hi, trying to build for an hour without success...
Please provide instructions for building
I am does not experience with GO and etc, but want to use 

Also binary images can be usable
Also arch linux repo packages can be usable

Thanks

**Comment by ds-voix** [comment]
Hi,
Please, use [X switcher v1.0 pre-release](https://github.com/ds-voix/xswitcher). It is now stable enough and fully customizable (all functionality except of "Exec" action).
The precompiled static binary is also placed under "bin/" directory.

I use
`go build -o xswitcher -ldflags "-s -w" --tags static_all src/*.go && chmod +xs xswitcher`
to build. There must be (libX11-devel | libx11-dev) + (libXmu-devel | libxmu-dev) libraries installed (of course, the package name depends on Your distro).

I don't plan to support any distro. Feel free to maintain Your preferred one. I think it's easy enough to prepack debian-based .deb packages.  You can start with [this example](https://www.debian.org/doc/manuals/debmake-doc/ch04.en.html).
